name: Build, Test and Deploy

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: install backend dependencies
      run: 
        cd backend
        npm install
    - name: build backend
      run: 
        cd backend
        npm run build
  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Deploy Backend to production
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service-id: ${{ secrets.BACKEND_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: install frontend dependencies
        run: 
          cd frontend
          npm install
      - name: build backend
        run: 
          cd frontend
          npm run build
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Deploy Frontend to production
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service-id: ${{ secrets.FRONTEND_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true
  
